Command fixes
aidn3/hypixel-guild-discord-bridge pull request #109
Opened 2023-10-02 17:01 UTC by HyxonQz

Roulette - Increased chances to lose to be more realistic.
Catacombs - Added better level formatting. (50.100 -> 50)

2023-10-04 18:04 UTC, aidn3 requested changes

2023-10-04 18:04 UTC, aidn3 commented on src/instance/minecraft/commands/RouletteCommand.ts
> +    const chance = 4 / 9 // why 4/9? No idea, but it works
change the comment to something useful.

2023-10-04 18:10 UTC, HyxonQz commented on src/instance/minecraft/commands/RouletteCommand.ts
> +    const chance = 4 / 9 // why 4/9? No idea, but it works
Fine.

2023-10-14 19:34 UTC, aidn3 approved these changes

2023-10-14 19:34 UTC, merged